name: 'Build And Publish Image'
description: 'Builds and publishes image'
inputs:
  version:
    description: 'image tag'
    required: true
  dockerhub-username:
    description: 'dockerhub username'
    required: true
  dockerhub-password:
    description: 'dockerhub password'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-password }}
    - name: Build and Push image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: springcloud/baseimage:${{ inputs.version }}
